export const letter: string[] = [
`Happy 6th Anniversary, Adi kooo! I love youuu! 🤍`,
`Grabe, six years na tayo! Ang bilis, ’no? HAHAHAHAHA. Anim na taon ng lambingan, kulitan, tampuhan, at pagbabati. Ang dami na nating pinagdaanan, pero heto pa rin tayo. Sobrang thankful ako kasi ikaw pa rin ang kasama ko.`,
`Mag-aral ka lang diyan nang mabuti, ha? Kailangan mong makagraduate para maabot mo yung mga pangarap mo, tapos makaipon na rin tayo para sa mga plano natin. HAHAHAHAHA. Alam kong nakakapagod at nakaka-stress minsan, pero proud ako sa’yo, Adi. Kapag nahihirapan ka, sabihin mo lang sa akin. Tutulungan kita hanggang kaya ko.`,
`Pasensya na kung wala muna tayong mga alis ngayon kasi pareho tayong kapos. Gusto rin kitang ilabas, kumain ng gusto natin, at makasama nang hindi iniisip kung magkano pa yung matitira. Darating din tayo roon. Sa ngayon, unti-unti muna. Medyo maliit na lang naman ang binabayaran kong utang, kaya may pag-asa na ulit ang ating mga gala! HAHAHAHAHA.`,
`Huwag kang mag-alala, magce-celebrate pa rin tayo kahit late. Hindi naman kailangang sa mismong araw lang natin iparamdam na espesyal tayo sa isa’t isa. Babawi tayo kapag kaya na, promise. At yung regalo ko sa’yo, hintayin mo lang, ha? Feeling ko magugustuhan mo yun, kaya sana sulit ang paghihintay mo. Bawal muna mangulit kung ano! HAHAHAHAHA.`,
`Sorry rin, Adi, kasi minsan nadadagdagan ko pa yung stress mo. Pagod ka na nga sa school, tapos may mga pagkakataong hindi pa kita naiintindihan. Minsan pareho tayong mainit ang ulo, kaya yung simpleng usapan nauuwi pa sa tampuhan. Sana mas matuto akong makinig at umintindi, lalo na kapag kailangan mo lang ng lambing at pahinga.`,
`At oo, sorry talaga sa mga oras na mas nauuna pa yung laro ko kaysa sa’yo. Alam kong hindi sapat yung puro “sorry” kung mauulit lang din. Kailangan kong ayusin yung oras ko at iparamdam sa’yo na may oras ako para sa atin. Ayokong kailangan mo pang makipag-agawan sa laro para lang makausap ako. Mahalaga ka sa akin, Adi, at gusto kong mas makita mo yun sa ginagawa ko.`,
`Naalala mo yung sinabi ko dati na tuwing sahod ko, bibigyan kita? Hindi ko yun nakalimutan. Hindi lang talaga natuloy noon dahil nagkautang-utang ako. Ngayon na mas maliit na yung binabayaran ko, gusto ko nang unti-unting tuparin yun ayon sa kaya ko. Gusto ko rin kasing may maibigay sa’yo at mapasaya ka kahit sa maliliit na bagay.`,
`Thank you kasi nandiyan ka pa rin para sa akin. Salamat sa pag-aalala, sa pag-intindi, sa lambing, at kahit sa mga sermon mo minsan. HAHAHAHAHA. Salamat din sa mga simpleng usapan at tawanan natin. Hindi man tayo laging may bonggang date o regalo, malaking bagay sa akin na may taong matatakbuhan ako at matatawag kong “Adi.”`,
`Sa susunod pang mga taon, sana marami pa tayong matupad na plano. Makagraduate ka, makaipon tayo, makapunta sa mga gusto nating puntahan, at makapag-celebrate nang hindi na kailangang mag-compute nang paulit-ulit. HAHAHAHAHA. Pero habang inaabot pa natin yun, sana alagaan natin kung anong meron tayo ngayon.`,
`Wala nang masyadong drama, baka sabihin mo ang haba ko nang mag-message. HAHAHAHAHA. Basta tandaan mo: andito lang ako para sa’yo. Kapag gusto mong magkuwento, magreklamo, umiyak, o tumawa sa kung anu-ano, nandito ang Adi mo.`,
`Thank you sa lahat-lahat, at sorry sa mga pagkukulang ko. Mahal na mahal kita. Happy 6th Anniversary sa atin, Adi ko. Ikaw pa rin ang gusto kong makasama sa mga susunod pang taon—at sa mga gala nating matutuloy din! HAHAHAHAHA. 🤍`
];
